// ==========================================
// モックデータ: 2026年ニュージーランドトロフィー
// raceId: 202606030511（中山・芝1600m・G2）
// オッズ: スポーツナビ中間オッズ（2026-04-10 19:46）参考
// 枠番割り当て: 15頭 → 枠1=1頭, 枠2〜8=各2頭
// ==========================================

import type { Race } from '../types';

export const MOCK_NZT_2026: Race = {
  raceId: '202606030511',
  name: 'ニュージーランドトロフィー',
  course: '中山',
  distance: 1600,
  surface: 'turf',
  fetchedAt: new Date('2026-04-10T19:46:00+09:00'),
  horses: [
    {
      id: 1,
      name: 'ハノハノ',
      waku: 1,
      odds: 14.6,
      fukuOddsMin: 4.2,
      fukuOddsMax: 8.1,
      jockey: '横山武史',
      trainer: '手塚貴久',
      weight: 466,
      weightDiff: 0,
      lastThreeF: 11.8,
    },
    {
      id: 2,
      name: 'マダックス',
      waku: 2,
      odds: 304.9,
      fukuOddsMin: 48.2,
      fukuOddsMax: 99.9,
      jockey: '丸田恭介',
      trainer: '小桧山悟',
      weight: 448,
      weightDiff: -2,
      lastThreeF: 12.4,
    },
    {
      id: 3,
      name: 'レザベーション',
      waku: 2,
      odds: 6.3,
      fukuOddsMin: 2.3,
      fukuOddsMax: 4.0,
      jockey: '川田将雅',
      trainer: '友道康夫',
      weight: 462,
      weightDiff: 4,
      lastThreeF: 11.5,
    },
    {
      id: 4,
      name: 'ヒズマスターピース',
      waku: 3,
      odds: 22.8,
      fukuOddsMin: 6.3,
      fukuOddsMax: 12.4,
      jockey: '北村友一',
      trainer: '池添学',
      weight: 472,
      weightDiff: 2,
      lastThreeF: 11.9,
    },
    {
      id: 5,
      name: 'ジーネキング',
      waku: 3,
      odds: 8.4,
      fukuOddsMin: 2.8,
      fukuOddsMax: 5.1,
      jockey: '坂井瑠星',
      trainer: '矢作芳人',
      weight: 458,
      weightDiff: -4,
      lastThreeF: 11.6,
    },
    {
      id: 6,
      name: 'シュペルリング',
      waku: 4,
      odds: 4.1,
      fukuOddsMin: 1.8,
      fukuOddsMax: 3.1,
      jockey: 'C.ルメール',
      trainer: '国枝栄',
      weight: 454,
      weightDiff: 0,
      lastThreeF: 11.3,
    },
    {
      id: 7,
      name: 'ロデオドライブ',
      waku: 4,
      odds: 38.5,
      fukuOddsMin: 9.7,
      fukuOddsMax: 19.8,
      jockey: '三浦皇成',
      trainer: '萩原清',
      weight: 444,
      weightDiff: 6,
      lastThreeF: 12.1,
    },
    {
      id: 8,
      name: 'スマイルカーブ',
      waku: 5,
      odds: 51.2,
      fukuOddsMin: 12.4,
      fukuOddsMax: 25.6,
      jockey: '岩田望来',
      trainer: '安達昭夫',
      weight: 468,
      weightDiff: -6,
      lastThreeF: 12.2,
    },
    {
      id: 9,
      name: 'ブルズアイプリンス',
      waku: 5,
      odds: 18.3,
      fukuOddsMin: 5.4,
      fukuOddsMax: 10.7,
      jockey: '幸英明',
      trainer: '高野友和',
      weight: 476,
      weightDiff: 2,
      lastThreeF: 11.7,
    },
    {
      id: 10,
      name: 'ジーティーシンドウ',
      waku: 6,
      odds: 3.2,
      fukuOddsMin: 1.5,
      fukuOddsMax: 2.6,
      jockey: '戸崎圭太',
      trainer: '相沢郁',
      weight: 486,
      weightDiff: 0,
      lastThreeF: 11.2,
    },
    {
      id: 11,
      name: 'ゴーラッキー',
      waku: 6,
      odds: 77.4,
      fukuOddsMin: 18.6,
      fukuOddsMax: 38.4,
      jockey: '菊沢一樹',
      trainer: '菊沢隆徳',
      weight: 452,
      weightDiff: -2,
      lastThreeF: 12.3,
    },
    {
      id: 12,
      name: 'アルデトップガン',
      waku: 7,
      odds: 10.7,
      fukuOddsMin: 3.4,
      fukuOddsMax: 6.5,
      jockey: '横山和生',
      trainer: '木村哲也',
      weight: 460,
      weightDiff: 4,
      lastThreeF: 11.9,
    },
    {
      id: 13,
      name: 'ガリレア',
      waku: 7,
      odds: 5.8,
      fukuOddsMin: 2.1,
      fukuOddsMax: 3.7,
      jockey: '藤岡佑介',
      trainer: '中内田充正',
      weight: 456,
      weightDiff: 0,
      lastThreeF: 11.4,
    },
    {
      id: 14,
      name: 'ディールメーカー',
      waku: 8,
      odds: 29.6,
      fukuOddsMin: 7.8,
      fukuOddsMax: 15.9,
      jockey: '田辺裕信',
      trainer: '田中博康',
      weight: 470,
      weightDiff: -2,
      lastThreeF: 12.0,
    },
    {
      id: 15,
      name: 'ミリオンクラウン',
      waku: 8,
      odds: 44.1,
      fukuOddsMin: 10.9,
      fukuOddsMax: 22.3,
      jockey: '松山弘平',
      trainer: '音無秀孝',
      weight: 442,
      weightDiff: 2,
      lastThreeF: 12.1,
    },
  ],
};
